# Generated by Django 5.2.3 on 2025-07-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_grade_student_alter_grade_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(db_column='class', max_length=100, null=True),
        ),
    ]
