# Generated by Django 5.2.3 on 2025-07-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_lastname_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(db_column='class', max_length=100, null=True, verbose_name='Class'),
        ),
    ]
