# Generated by Django 5.2.3 on 2025-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_subject_teacher_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=100, unique=True, verbose_name='Subject'),
        ),
    ]
