# Generated by Django 5.2.3 on 2025-08-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_subject_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade_object',
            new_name='GradeObject',
        ),
    ]
