# Generated by Django 5.2.3 on 2025-08-11 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_rename_grade_object_gradeobject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='class_name',
            field=models.CharField(db_column='class', max_length=100, null=True, unique=True, verbose_name='Class'),
        ),
        migrations.CreateModel(
            name='Subject2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject')),
                ('klass', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, to='school.klass', verbose_name='Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
        ),
    ]
