# Generated by Django 5.2.3 on 2025-08-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_klass_class_name_subject2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeobject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject2'),
        ),
    ]
