# Generated by Django 5.2.3 on 2025-08-11 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_gradeobject_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeobject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='klass',
            field=models.ForeignKey(db_column='class', default=1, on_delete=django.db.models.deletion.CASCADE, to='school.klass', verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Subject2',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
            preserve_default=False,
        ),
    ]
